sudo: true
matrix:
  include:
  - os: linux
    language: python
    python: '3.6'
    before_install:
      - python3 --version
  - os: osx
    language: generic
    python: '3.7'
    before_install:
      - python3 --version
install:
  - python3 -m pip install --upgrade pip
  - pip install --upgrade setuptools
  - make install
script:
  - pip install pyinstaller
  - pyinstaller --distpath dist/$TRAVIS_OS_NAME gui.spec
before_deploy:
  - git config --local user.name "Travis"
  - git config --local user.email "travis@travis-ci.org"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  - tar -czvf dist/DEXBot-gui-$TRAVIS_OS_NAME-$TRAVIS_TAG.tar.gz dist/$TRAVIS_OS_NAME/DEXBot-gui
deploy:
  - provider: releases
    skip_cleanup: true
    body: Automated release from Travis CI with added files from AppVeyor build
    api_key:
      secure: aVRcq/JDh7HoGcDrjZoKWaGZr1Ie7hxzxzYGNqb8p7F7rWuTSanlEZRQ+4mq2lAFq+ase9lycyZXu1KFKSf7iEGBeqMudMOVVc2j87sQEH7MKKX/bZrapvw4mxvu+kGJQXpNI70tB6hJmVvNtZpleqsiFs0i2R2pAnVvmVajxfxoXrmz68oS172HGdQ2RzuPE7fjvK8JclJ10jd1dfD82XEo6GkX9TqDe2NhaMZvf/ROKhSC35C2DnTKWuSAI7zGcX8GbcSqlskCJYdDv5fgE2banUDuzJuT4TmsEvfIMa7+xnaDStBq7zxEiLPNq0wTZEbrdY9jV/IhWKjOFaI58LGHOedA4dvUKiMuXF4FtBjhUC4UGNwn9g0wZU/q/GtiyRzRXgQ9JYCfM5r1UDkh+4xm2VB7NQ1NoA7ajidamqBamRmHdh0wZI6NwtKYPjGEX1QUBNlt3HXvpLU26j39gjMcduj8kiFh05RlWq41EgbQAPMR1256nw9yGRrnTA7M9QEfmjNvpb4CT1FWmBDtkALzskLSZOts4iZ6vQvWGZkntd7IeZ9Rr4ImX99vZIwYWNL9n6VJW75VlwF/E0Uxqxs8WkYUDFayfySxADpVwkmiR9d3cahzu9UbqVHzH8a0Uvko9TxIHhTjep/ER5dXu2cSObdTqKRp1FRQksI8/Oo=
    file: dist/*.tar.gz
    file_glob: true
    draft: true
    on:
      tags: true