version: 0.1.{build}

image: Visual Studio 2015

environment:
  matrix:
    # Python 3.6.6 - 64-bit
    - PYTHON: "C:\\Python36-x64"

#---------------------------------#
#        Build                    #
#---------------------------------#

install:
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%;C:\MinGW\bin
  - copy c:\MinGW\bin\mingw32-make.exe c:\MinGW\bin\make.exe
  - copy c:\Python36-x64\python.exe c:\Python36-x64\python3.exe
  - python --version
  - make install
  - make package
  - copy /Y C:\projects\dexbot\dist\DEXBot-gui.exe C:\projects\dexbot\installer\windows\msi\DEXBot.exe
  - '7z a DEXBot-gui-win64.zip %APPVEYOR_BUILD_FOLDER%\dist\DEXBot-gui.exe'
  # read dexbot version from __init__.py
  - for /f "delims== eol=# tokens=1,2" %%G in (.\dexbot\__init__.py) do set %%G=%%H
  # set to version and replace ' with empty character
  - set ApplicationVersion=%VERSION:'=%

# visual studio configuration
configuration:
- Release
platform: x86
build:
  verbosity: normal

# @TODO: Run tests..
test_script:
  - "echo tests..."

# artifact as relativ path to the build folder C:\projects\dexbot
artifacts:
  - path: DEXBot-gui-win64.zip
    name: DEXBot-gui-win64.zip
  - path: installer\windows\bundle\bin\%CONFIGURATION%\DEXBot-installer.exe
    name: DEXBot-installer.exe

#---------------------------------#
#        Deployment               #
#---------------------------------#

shallow_clone: false

clone_depth: 1

deploy:
  - provider: GitHub
    draft: false
    prerelease: false
    force_update: true
    auth_token:
      secure: 9qvwlVUHFBV4GwMz1Gu2HSnqU8Ex2nv5dsY4mVNCurrb+6ULIoHPgbvJPWTo3qV6
    on:
      appveyor_repo_tag: true     # deploy on tag push only
