version: 1.0.{build}

image: Visual Studio 2015

environment:
  matrix:
    # Python 3.6 - 32-bit
    #- PYTHON: "C:\\Python36"
    # Python 3.6 - 64-bit
    - PYTHON: "C:\\Python36-x64"

#---------------------------------#
#        build                    #
#---------------------------------#

build: off

configuration: Release

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "pip install pyinstaller click-datetime PyQt5 pyqt-distutils"
  - "python setup.py install"

after_test:
  - "pyinstaller app.spec"
  - "pyinstaller cli.spec"
  - '7z a DEXBot-win64.zip %APPVEYOR_BUILD_FOLDER%\dist\DEXBot-gui.exe %APPVEYOR_BUILD_FOLDER%\dist\DEXBot-cli.exe'

# @TODO: Run tests..
test_script:
  - "echo tests..."

artifacts:
  - path: DEXBot-win64.zip
    name: DEXBot-win64.zip

#---------------------------------#
#        deployment               #
#---------------------------------#

shallow_clone: false

clone_depth: 1

deploy:
  - provider: GitHub
    artifact: DEXBot-win64.zip
    draft: false
    prerelease: false
    force_update: true
    auth_token:
      secure: 9qvwlVUHFBV4GwMz1Gu2HSnqU8Ex2nv5dsY4mVNCurrb+6ULIoHPgbvJPWTo3qV6
    on:
      appveyor_repo_tag: true     # deploy on tag push only

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:
  - provider: Slack
    auth_token:
      secure: G9OMj9l2s3+lX8cRiNXXhuQJpnnjcBc0cqP8gzkdKVWqGA8vBTOIPGxD/536VKpeBH/5dJFQWT+vmnGS+XciaCg4hh5s6hDpnvePq2+uEYE=
    channel: '#ci'
