node: wss://node.testnet.bitshares.eu

bots: {
  Bot 1: {
  market: TESTUSD/TEST, account: nikolay-codaone, module: dexbot.strategies.simple,
    target: {center_price: 42.025, amount: 0.01, spread: 5.0}, strategy: Simple Strategy}}
